# Generated by Django 4.0.6 on 2022-07-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_apellido_user_nombre_user_rol_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refTienda',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
