# Generated by Django 4.0.6 on 2022-07-10 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0003_productoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoventa',
            name='refVenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='refLocalComercial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.localcomercial'),
        ),
    ]
