# Generated by Django 4.0.6 on 2022-07-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_venta_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('esVisible', models.BooleanField(default=False)),
                ('esNuevo', models.BooleanField(default=True)),
                ('refLocalComercial', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.localcomercial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('esVisible', models.BooleanField(default=False)),
                ('esNuevo', models.BooleanField(default=True)),
                ('isBestProduct', models.BooleanField(default=False)),
                ('refCategoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseApp.categoria')),
            ],
        ),
    ]
