# Generated by Django 4.0.6 on 2022-07-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_categoria_productocategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipoEntrega', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('direccionEntrega', models.TextField()),
                ('telefonoEntrega', models.CharField(max_length=50)),
                ('nombrePedido', models.CharField(max_length=50)),
                ('precioEnvio', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('notaEspecial', models.TextField()),
                ('precioTotal', models.IntegerField()),
                ('precioUnitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
