# Generated by Django 4.0.6 on 2022-07-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0008_orden_reflocalcomercial_orden_refventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
