# Generated by Django 4.0.6 on 2022-07-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0009_productocategoria_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank='', default='', upload_to='fotos/'),
        ),
    ]
