# Generated by Django 4.0.6 on 2022-07-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0010_categoria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='imagen',
            field=models.ImageField(blank='', default='', upload_to='fotos/productos'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank='', default='', upload_to='fotos/categorias'),
        ),
    ]
