# Generated by Django 4.0.6 on 2022-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0012_remove_productoventa_notaespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='entregaDelivery',
            field=models.BooleanField(default=False),
        ),
    ]
