# Generated by Django 4.0.6 on 2022-08-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0013_orden_entregadelivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estadoPago',
            field=models.CharField(default='NO_PAGADO', max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='estadoVenta',
            field=models.CharField(default='FINALIZADA', max_length=50),
        ),
    ]
