# Generated by Django 4.0.6 on 2022-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0014_venta_estadopago_venta_estadoventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='pagoDeliveryEfectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localcomercial',
            name='pagoDeliveryMercadopago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localcomercial',
            name='pagoDeliveryPos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localcomercial',
            name='pagoRetiroLocalEfectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localcomercial',
            name='pagoRetiroLocalMercadopago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='localcomercial',
            name='pagoRetiroLocalPos',
            field=models.BooleanField(default=False),
        ),
    ]
