# Generated by Django 4.0.6 on 2022-08-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0015_localcomercial_pagodeliveryefectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='tieneRetiroLocal',
            field=models.BooleanField(default=False),
        ),
    ]
