# Generated by Django 4.0.6 on 2022-08-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0016_localcomercial_tieneretirolocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tiempoEntrega',
            field=models.CharField(default='Lo antes posible', max_length=255),
        ),
    ]
