# Generated by Django 4.0.6 on 2022-08-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0018_orden_emailentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
    ]
