# Generated by Django 4.0.6 on 2022-08-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0019_localcomercial_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='imagen',
            field=models.ImageField(blank='', default='', upload_to='fotos/localesComerciales'),
        ),
    ]
