# Generated by Django 4.0.6 on 2022-08-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0020_localcomercial_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
