# Generated by Django 4.0.6 on 2022-08-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0021_localcomercial_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='link',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
