# Generated by Django 4.0.6 on 2022-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0022_alter_localcomercial_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='comuna',
            field=models.CharField(default='SIN COMUNA', max_length=30),
        ),
        migrations.AddField(
            model_name='localcomercial',
            name='region',
            field=models.CharField(default='SIN REGIÓN', max_length=30),
        ),
    ]
