# Generated by Django 4.0.6 on 2022-09-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0025_alter_localcomercial_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='comuna',
            field=models.CharField(default='SIN COMUNA', max_length=50),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='region',
            field=models.CharField(default='SIN REGIÓN', max_length=50),
        ),
    ]
