# Generated by Django 4.0.6 on 2022-09-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0026_alter_localcomercial_comuna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='privateKeyMercadopago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='publicKeyMercadopago',
            field=models.CharField(max_length=50),
        ),
    ]
