# Generated by Django 4.0.6 on 2022-10-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0028_remove_localcomercial_privatekeymercadopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='accessTokenMercadopago',
            field=models.CharField(default='--', max_length=80),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='publicKeyMercadopago',
            field=models.CharField(max_length=80),
        ),
    ]
