# Generated by Django 4.0.6 on 2022-10-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0029_alter_localcomercial_accesstokenmercadopago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mercadopago_collection_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='mercadopago_collection_status',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='mercadopago_merchant_order_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='mercadopago_payment_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='mercadopago_preference_id',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='mercadopago_status',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='pagadoViaMercadopago',
            field=models.BooleanField(default=False),
        ),
    ]
