# Generated by Django 4.0.6 on 2022-10-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0030_venta_mercadopago_collection_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='mercadopago_external_reference',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
